import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { getMedicines, Medicine } from '@/lib/data';
import { scheduleReminder } from '@/lib/notifications';

export default function DashboardScreen() {
  const [medicines, setMedicines] = useState<Medicine[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [message, setMessage] = useState('');
  const load = useCallback(async () => { try { setMedicines(await getMedicines()); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not load medicines.'); } finally { setLoading(false); setRefreshing(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const schedule = async (medicine: Medicine) => { try { const [hour, minute] = medicine.time.split(':').map(Number); await scheduleReminder(medicine.name, medicine.dosage, hour, minute); setMessage(`Daily reminder set for ${medicine.time}.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not set reminder.'); } };
  return <SafeAreaView style={styles.page}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); load(); }} />} contentContainerStyle={styles.content}>
    <View style={styles.header}><View><Text style={styles.eyebrow}>TUESDAY, OCTOBER 6</Text><Text style={styles.title}>Good morning</Text></View><View style={styles.avatar}><Text style={styles.avatarText}>MT</Text></View></View>
    <View style={styles.hero}><View><Text style={styles.heroLabel}>YOUR DAILY RHYTHM</Text><Text style={styles.heroTitle}>{medicines.length ? `${medicines.length} medicines today` : 'A lighter day starts here'}</Text><Text style={styles.heroCopy}>{medicines.length ? 'Stay steady. One dose at a time.' : 'Add your first medicine to begin.'}</Text></View><Text style={styles.heroMark}>✦</Text></View>
    {message ? <Text style={styles.message}>{message}</Text> : null}<View style={styles.sectionHeader}><Text style={styles.sectionTitle}>Today’s medicines</Text><Text style={styles.count}>{medicines.length}</Text></View>
    {loading ? <ActivityIndicator color="#157f78" style={{ marginTop: 30 }} /> : medicines.length === 0 ? <View style={styles.empty}><Text style={styles.emptyIcon}>＋</Text><Text style={styles.emptyTitle}>Nothing scheduled yet</Text><Text style={styles.emptyCopy}>Your medicine list will appear here once you add a dose.</Text></View> : medicines.map((medicine) => <View style={styles.card} key={medicine.id}><View style={styles.time}><Text style={styles.timeText}>{medicine.time}</Text><Text style={styles.timeLabel}>DAILY</Text></View><View style={styles.medicine}><Text style={styles.medicineName}>{medicine.name}</Text><Text style={styles.medicineMeta}>{medicine.dosage} · {medicine.quantity} remaining</Text></View><Pressable onPress={() => schedule(medicine)}><Text style={styles.bell}>♧</Text></Pressable></View>)}
  </ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: '#f6f8f6' }, content: { padding: 20, paddingBottom: 32 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 }, eyebrow: { color: '#6f817b', fontSize: 11, fontWeight: '700', letterSpacing: 1.2 }, title: { color: '#17332f', fontSize: 30, fontWeight: '800', marginTop: 4 }, avatar: { backgroundColor: '#d8ece5', borderRadius: 22, width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: '#157f78', fontWeight: '800' }, hero: { backgroundColor: '#173f3a', borderRadius: 22, padding: 22, flexDirection: 'row', justifyContent: 'space-between', overflow: 'hidden' }, heroLabel: { color: '#a8d3c4', fontSize: 11, fontWeight: '700', letterSpacing: 1 }, heroTitle: { color: '#fff', fontSize: 22, fontWeight: '800', marginTop: 10 }, heroCopy: { color: '#d4e7e0', marginTop: 6 }, heroMark: { color: '#e68b4d', fontSize: 46 }, message: { color: '#157f78', backgroundColor: '#e1f2eb', padding: 12, borderRadius: 12, marginTop: 16 }, sectionHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 28, marginBottom: 12 }, sectionTitle: { color: '#17332f', fontSize: 20, fontWeight: '800' }, count: { color: '#157f78', backgroundColor: '#d8ece5', borderRadius: 12, paddingHorizontal: 8, paddingVertical: 3, fontWeight: '700' }, card: { alignItems: 'center', backgroundColor: '#fff', borderRadius: 18, flexDirection: 'row', marginBottom: 10, padding: 16, boxShadow: '0px 2px 10px rgba(22, 59, 53, 0.05)' }, time: { borderRightColor: '#e3ece8', borderRightWidth: 1, paddingRight: 14, width: 67 }, timeText: { color: '#17332f', fontSize: 17, fontWeight: '800' }, timeLabel: { color: '#8b9c95', fontSize: 9, fontWeight: '700', marginTop: 4 }, medicine: { flex: 1, paddingLeft: 14 }, medicineName: { color: '#17332f', fontSize: 16, fontWeight: '700' }, medicineMeta: { color: '#71817b', fontSize: 13, marginTop: 5 }, bell: { color: '#157f78', fontSize: 24 }, empty: { alignItems: 'center', backgroundColor: '#fff', borderRadius: 18, padding: 32 }, emptyIcon: { color: '#e68b4d', fontSize: 34 }, emptyTitle: { color: '#17332f', fontSize: 17, fontWeight: '700', marginTop: 10 }, emptyCopy: { color: '#71817b', lineHeight: 20, marginTop: 6, textAlign: 'center' } });
