import { useCallback, useEffect, useState } from 'react';
import { Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { deleteMedicine, getMedicines, Medicine, saveMedicine } from '@/lib/data';

const blank = { name: '', dosage: '', time: '08:00', quantity: '30' };

export default function MedicinesScreen() {
  const [medicines, setMedicines] = useState<Medicine[]>([]);
  const [form, setForm] = useState(blank);
  const [editing, setEditing] = useState<string>();
  const [showForm, setShowForm] = useState(false);
  const [error, setError] = useState('');
  const load = useCallback(async () => { try { setMedicines(await getMedicines()); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load medicines.'); } }, []);
  useEffect(() => { load(); }, [load]);
  const submit = async () => { if (!form.name.trim() || !form.dosage.trim() || !/^\d{2}:\d{2}$/.test(form.time) || Number.isNaN(Number(form.quantity))) return setError('Enter a name, dosage, time, and quantity.'); try { await saveMedicine({ name: form.name.trim(), dosage: form.dosage.trim(), time: form.time, quantity: Number(form.quantity) }, editing); setForm(blank); setEditing(undefined); setShowForm(false); setError(''); load(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not save medicine.'); } };
  const remove = (medicine: Medicine) => Alert.alert('Delete medicine?', `Remove ${medicine.name} from your list?`, [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: async () => { await deleteMedicine(medicine.id); load(); } }]);
  const edit = (medicine: Medicine) => { setForm({ name: medicine.name, dosage: medicine.dosage, time: medicine.time, quantity: String(medicine.quantity) }); setEditing(medicine.id); setShowForm(true); };
  return <SafeAreaView style={styles.page}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><View><Text style={styles.eyebrow}>YOUR ROUTINE</Text><Text style={styles.title}>Medicines</Text></View><Pressable style={styles.add} onPress={() => { setForm(blank); setEditing(undefined); setShowForm(true); }}><Text style={styles.addText}>＋ Add</Text></Pressable></View>
    {showForm && <View style={styles.form}><Text style={styles.formTitle}>{editing ? 'Edit medicine' : 'Add medicine'}</Text>{(['name', 'dosage', 'time', 'quantity'] as const).map((field) => <TextInput key={field} placeholder={field === 'name' ? 'Medicine name' : field === 'dosage' ? 'Dosage, e.g. 500mg' : field === 'time' ? 'Time, e.g. 08:00' : 'Quantity'} placeholderTextColor="#8a9792" keyboardType={field === 'quantity' ? 'numeric' : field === 'time' ? 'numbers-and-punctuation' : 'default'} value={form[field]} onChangeText={(value) => setForm({ ...form, [field]: value })} style={styles.input} />)}<View style={styles.formActions}><Pressable onPress={() => setShowForm(false)}><Text style={styles.cancel}>Cancel</Text></Pressable><Pressable style={styles.save} onPress={submit}><Text style={styles.saveText}>Save medicine</Text></Pressable></View></View>}
    {error ? <Text style={styles.error}>{error}</Text> : null}{medicines.map((medicine) => <View style={styles.card} key={medicine.id}><View style={styles.pill}><Text style={styles.pillText}>Rx</Text></View><View style={styles.details}><Text style={styles.name}>{medicine.name}</Text><Text style={styles.meta}>{medicine.dosage} · {medicine.time}</Text><Text style={styles.stock}>{medicine.quantity} doses remaining</Text></View><View><Pressable onPress={() => edit(medicine)}><Text style={styles.action}>Edit</Text></Pressable><Pressable onPress={() => remove(medicine)}><Text style={styles.delete}>Delete</Text></Pressable></View></View>)}{!medicines.length && !showForm ? <View style={styles.empty}><Text style={styles.emptyTitle}>Your medicine shelf is empty</Text><Text style={styles.meta}>Add a dose to build your daily routine.</Text></View> : null}
  </ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: '#f6f8f6' }, content: { padding: 20 }, header: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 24 }, eyebrow: { color: '#6f817b', fontSize: 11, fontWeight: '700', letterSpacing: 1.2 }, title: { color: '#17332f', fontSize: 30, fontWeight: '800', marginTop: 4 }, add: { backgroundColor: '#157f78', borderRadius: 14, paddingHorizontal: 15, paddingVertical: 11 }, addText: { color: '#fff', fontWeight: '700' }, form: { backgroundColor: '#e1f2eb', borderRadius: 18, gap: 10, marginBottom: 16, padding: 16 }, formTitle: { color: '#17332f', fontSize: 18, fontWeight: '800', marginBottom: 2 }, input: { backgroundColor: '#fff', borderRadius: 12, color: '#17332f', padding: 13 }, formActions: { alignItems: 'center', flexDirection: 'row', justifyContent: 'flex-end', gap: 18, marginTop: 4 }, cancel: { color: '#536760', fontWeight: '700' }, save: { backgroundColor: '#157f78', borderRadius: 10, paddingHorizontal: 13, paddingVertical: 10 }, saveText: { color: '#fff', fontWeight: '700' }, error: { backgroundColor: '#fbe4de', borderRadius: 10, color: '#a6432e', marginBottom: 12, padding: 11 }, card: { alignItems: 'center', backgroundColor: '#fff', borderRadius: 18, flexDirection: 'row', marginBottom: 10, padding: 15 }, pill: { alignItems: 'center', backgroundColor: '#fce7d8', borderRadius: 14, height: 45, justifyContent: 'center', width: 45 }, pillText: { color: '#c66532', fontWeight: '800' }, details: { flex: 1, paddingHorizontal: 13 }, name: { color: '#17332f', fontSize: 16, fontWeight: '800' }, meta: { color: '#71817b', fontSize: 13, marginTop: 4 }, stock: { color: '#157f78', fontSize: 12, fontWeight: '700', marginTop: 7 }, action: { color: '#157f78', fontWeight: '700', padding: 5 }, delete: { color: '#b4533e', fontSize: 12, padding: 5 }, empty: { alignItems: 'center', backgroundColor: '#fff', borderRadius: 18, padding: 28, marginTop: 10 }, emptyTitle: { color: '#17332f', fontSize: 17, fontWeight: '700', marginBottom: 5 } });