import { useState } from 'react';
import * as Location from 'expo-location';
import { ActivityIndicator, Alert, Linking, Pressable, SafeAreaView, StyleSheet, Text, View } from 'react-native';
import { postApi } from '@/lib/api';
import PharmacyMap from '@/components/PharmacyMap';

type Pharmacy = { id: string | number; name: string; address: string; phone: string; lat: number; lng: number; distance: number };

export default function PharmaciesScreen() {
  const [location, setLocation] = useState<{ latitude: number; longitude: number }>();
  const [pharmacies, setPharmacies] = useState<Pharmacy[]>([]);
  const [loading, setLoading] = useState(false);
  const find = async () => { setLoading(true); const permission = await Location.requestForegroundPermissionsAsync(); if (!permission.granted) { setLoading(false); return Alert.alert('Location needed', 'Allow location access to find nearby pharmacies.'); } const current = await Location.getCurrentPositionAsync({}); const next = { latitude: current.coords.latitude, longitude: current.coords.longitude }; setLocation(next); try { const result = await postApi<{ pharmacies: Pharmacy[] }>('/api/pharmacies', { latitude: next.latitude, longitude: next.longitude }); setPharmacies(result.pharmacies); } catch (e) { Alert.alert('Could not search', e instanceof Error ? e.message : 'Try again.'); } finally { setLoading(false); } };
  return <SafeAreaView style={styles.page}><View style={styles.content}><Text style={styles.eyebrow}>AROUND YOU</Text><Text style={styles.title}>Pharmacies</Text><Text style={styles.copy}>Find an open pharmacy nearby when you need one.</Text><Pressable style={styles.button} onPress={find}><Text style={styles.buttonText}>{loading ? 'Finding nearby...' : 'Find near me'}</Text></Pressable>{location ? <PharmacyMap location={location} pharmacies={pharmacies} /> : <View style={styles.mapEmpty}>{loading ? <ActivityIndicator color="#157f78" /> : <Text style={styles.mapHint}>Your map will appear after location access.</Text>}</View>}{pharmacies.map((pharmacy) => <Pressable key={String(pharmacy.id)} style={styles.card} onPress={() => Linking.openURL(`https://maps.google.com/?q=${pharmacy.lat},${pharmacy.lng}`)}><View style={styles.pin}><Text>⌖</Text></View><View style={{ flex: 1 }}><Text style={styles.name}>{pharmacy.name}</Text><Text style={styles.address}>{pharmacy.address}</Text><Text style={styles.distance}>{pharmacy.distance.toFixed(1)} km away</Text></View><Text style={styles.arrow}>›</Text></Pressable>)}</View></SafeAreaView>;
}

const styles = StyleSheet.create({ page: { backgroundColor: '#f6f8f6', flex: 1 }, content: { padding: 20 }, eyebrow: { color: '#6f817b', fontSize: 11, fontWeight: '700', letterSpacing: 1.2 }, title: { color: '#17332f', fontSize: 30, fontWeight: '800', marginTop: 4 }, copy: { color: '#61716c', fontSize: 16, marginTop: 10 }, button: { alignItems: 'center', backgroundColor: '#157f78', borderRadius: 13, marginTop: 18, padding: 15 }, buttonText: { color: '#fff', fontWeight: '800' }, map: { borderRadius: 18, height: 220, marginTop: 16 }, mapEmpty: { alignItems: 'center', backgroundColor: '#e4eee9', borderRadius: 18, height: 220, justifyContent: 'center', marginTop: 16 }, mapHint: { color: '#71817b' }, card: { alignItems: 'center', backgroundColor: '#fff', borderRadius: 16, flexDirection: 'row', marginTop: 10, padding: 14 }, pin: { alignItems: 'center', backgroundColor: '#d8ece5', borderRadius: 12, height: 40, justifyContent: 'center', marginRight: 12, width: 40 }, name: { color: '#17332f', fontWeight: '800' }, address: { color: '#71817b', fontSize: 12, marginTop: 3 }, distance: { color: '#157f78', fontSize: 12, fontWeight: '700', marginTop: 5 }, arrow: { color: '#157f78', fontSize: 26 } });