import { Alert, Pressable, SafeAreaView, StyleSheet, Text, View } from 'react-native';
import { Link } from 'expo-router';
import { supabase } from '@/lib/supabase';
import { requestReminderPermission } from '@/lib/notifications';

export default function ProfileScreen() {
  const signOut = () => Alert.alert('Sign out?', 'You can sign back in any time.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Sign out', style: 'destructive', onPress: () => supabase.auth.signOut() }]);
  return <SafeAreaView style={styles.page}><View style={styles.content}><Text style={styles.eyebrow}>YOUR SPACE</Text><Text style={styles.title}>Profile</Text><View style={styles.profile}><View style={styles.avatar}><Text style={styles.avatarText}>MT</Text></View><View><Text style={styles.name}>MediTrack+ member</Text><Text style={styles.meta}>Your health routine, in one place</Text></View></View><Link href="/chatbot" asChild><Pressable style={styles.row}><Text style={styles.rowIcon}>✦</Text><View style={styles.rowCopy}><Text style={styles.rowTitle}>Medication assistant</Text><Text style={styles.meta}>Ask a general medicine question</Text></View><Text style={styles.arrow}>›</Text></Pressable></Link><Pressable style={styles.row} onPress={async () => { const allowed = await requestReminderPermission(); Alert.alert(allowed ? 'Reminders enabled' : 'Reminders not enabled', allowed ? 'You can now receive medicine alerts.' : 'Enable notifications in your device settings.'); }}><Text style={styles.rowIcon}>◷</Text><View style={styles.rowCopy}><Text style={styles.rowTitle}>Medicine reminders</Text><Text style={styles.meta}>Manage notification permission</Text></View><Text style={styles.arrow}>›</Text></Pressable><Pressable style={styles.row} onPress={() => Alert.alert('Privacy', 'Your mobile app uses Supabase authentication and never stores OpenAI or Twilio secrets on the device.')}><Text style={styles.rowIcon}>◇</Text><View style={styles.rowCopy}><Text style={styles.rowTitle}>Privacy & security</Text><Text style={styles.meta}>How your data is handled</Text></View><Text style={styles.arrow}>›</Text></Pressable><Pressable style={styles.signOut} onPress={signOut}><Text style={styles.signOutText}>Sign out</Text></Pressable></View></SafeAreaView>;
}

const styles = StyleSheet.create({ page: { backgroundColor: '#f6f8f6', flex: 1 }, content: { padding: 20 }, eyebrow: { color: '#6f817b', fontSize: 11, fontWeight: '700', letterSpacing: 1.2 }, title: { color: '#17332f', fontSize: 30, fontWeight: '800', marginTop: 4 }, profile: { alignItems: 'center', backgroundColor: '#173f3a', borderRadius: 18, flexDirection: 'row', marginTop: 24, padding: 18 }, avatar: { alignItems: 'center', backgroundColor: '#d8ece5', borderRadius: 24, height: 48, justifyContent: 'center', marginRight: 13, width: 48 }, avatarText: { color: '#157f78', fontWeight: '800' }, name: { color: '#fff', fontSize: 16, fontWeight: '800' }, meta: { color: '#71817b', fontSize: 12, marginTop: 4 }, row: { alignItems: 'center', backgroundColor: '#fff', borderRadius: 16, flexDirection: 'row', marginTop: 12, padding: 16 }, rowIcon: { color: '#e68b4d', fontSize: 22, width: 32 }, rowCopy: { flex: 1 }, rowTitle: { color: '#17332f', fontWeight: '800' }, arrow: { color: '#157f78', fontSize: 26 }, signOut: { alignItems: 'center', borderColor: '#d9e3de', borderRadius: 13, borderWidth: 1, marginTop: 28, padding: 15 }, signOutText: { color: '#b4533e', fontWeight: '800' } });